export type Student = {id:string; name:string; birth:string; shirt:string; gender:string; cpf:string; phone:string; email:string; street:string; number:string; neighborhood:string; city:string; state:string; enrollment:string; plan:string; value:number; due:number; status:string; level:string; goal:string; pace:string; frequency:number; experience:string; availability:string; race:string; raceDate:string; raceDistance:string; medical:string; notes:string};
export type Workout = {id:string; type:string; title:string; warmup:number; reps:number; distance:number; target:string; rest:number; cooldown:number; pace:string; duration:number; notes:string};
export const today = new Date(2026,9,8);
const names=['Marina Almeida','Rafael Oliveira','Beatriz Santos','Lucas Ferreira','Camila Rodrigues','Pedro Martins','Juliana Costa','André Lima','Fernanda Rocha','Gustavo Ribeiro','Letícia Barros','Bruno Mendes'];
export const students:Student[]=names.map((name,i)=>({id:String(i+1),name,birth:`${1987+i%12}-${i<3?'10':String(i+1).padStart(2,'0')}-${String(i<3?10+i*4:8+i).padStart(2,'0')}`,shirt:['M','G','P'][i%3],gender:i%2?'Masculino':'Feminino',cpf:'000.000.000-00',phone:'(00) 00000-0000',email:`aluno${i+1}@example.com`,street:'Rua Exemplo',number:String(100+i),neighborhood:'Bairro Modelo',city:'Cidade Exemplo',state:'CE',enrollment:`${2026}-${String(i+1).padStart(3,'0')}`,plan:i%3?'Corrida presencial':'Corrida online',value:i%3?180:140,due:[10,10,15,12,20,15,10,20,25,12,15,25][i],status:i===11?'Pausado':'Ativo',level:['Intermediário','Avançado','Iniciante'][i%3],goal:['10 km','21 km','5 km'][i%3],pace:['5:45','4:50','6:30'][i%3],frequency:3,experience:['2 anos','4 anos','6 meses'][i%3],availability:'Domingo, terça e quinta · manhã',race:i%2?'Meia da Primavera':'Circuito Parque Verde',raceDate:i%2?'2026-11-08':'2026-10-25',raceDistance:i%2?'21 km':'10 km',medical:i===0?'Histórico fictício de desconforto no joelho direito. Observar relato de dor.':'Nenhuma restrição informada no cadastro fictício.',notes:'Prefere treinar pela manhã. Objetivo: evoluir com consistência.'}));
const base={warmup:5,reps:6,distance:200,target:'50 s',rest:1,cooldown:5,pace:'6:00',duration:2,notes:''};
export const templates:Workout[]=[{...base,id:'t1',type:'Rodagem',title:'Rodagem leve',distance:5,pace:'6:30'},{...base,id:'t2',type:'Rodagem',title:'Rodagem longa',distance:10},{...base,id:'t3',type:'Tiros',title:'Tiros 200 m'},{...base,id:'t4',type:'Tiros',title:'Tiros 400 m',distance:400,target:'1 min 50 s'},{...base,id:'t5',type:'Tiros',title:'Tiros 800 m',distance:800,reps:4,target:'4 min'},{...base,id:'t6',type:'Intervalado por tempo',title:'Intervalado por tempo',reps:8,duration:2}];
export type Schedule=Record<string,Workout[]>;
export const initialSchedule:Schedule={};
for (const s of students) for(let w=-1;w<=1;w++) for (const d of [0,2,4]) { if(w===1&&Number(s.id)>8) continue; initialSchedule[`${s.id}:${w}:${d}`]=[{...templates[d===0?1:d===2?2:0],id:`${s.id}-${w}-${d}`}]; }
export const summary=(w:Workout)=>w.type==='Rodagem'?`${w.distance} km · ${w.pace}/km`:w.type==='Tiros'?`${w.reps} × ${w.distance} m · ${w.target}`:`${w.reps} × ${w.duration} min · pausa ${w.rest} min`;
export const initials=(name:string)=>name.split(' ').map(n=>n[0]).slice(0,2).join('');
export const dateLabel=(date:string)=>new Date(date+'T12:00:00').toLocaleDateString('pt-BR');
export const money=(n:number)=>n.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
