import {useState, useEffect, type ReactNode} from 'react';
import {createRoot} from 'react-dom/client';
import {Home, Users, CalendarDays, MoreHorizontal, Plus, ChevronRight, ChevronLeft, ArrowLeft, ArrowRight, Search, SlidersHorizontal, Cake, Flag, Wallet, Layers, Copy, Check, LogOut, Heart, X} from 'lucide-react';
import {students as seed, templates, initialSchedule, summary, initials, dateLabel, money, today, days, dayNames, weekDate, shortDate, scheduleKey, normalize, assessments, emptyStudent, type Student, type Workout, type Schedule} from './data';
import Modal from './Modal';
import StudentForm from './StudentForm';
import WorkoutEditor from './WorkoutEditor';
import WorkoutActions from './WorkoutActions';
import {cloneWorkout, saveSession, duplicateSession, deleteSession, duplicatePreviousWeek} from './scheduleOperations';
import './style.css';
type Page = 'home' | 'students' | 'workouts' | 'more' | 'profile';
type Detail = '' | 'data' | 'assessments' | 'plan';
type Sheet = {type:'add'; day:number} | {type:'templates'; day:number} | {type:'week'} | {type:'workout'; day:number; workout:Workout} | {type:'delete'; day:number; workout:Workout} | null;
const nav = [{id:'home',label:'Início',icon:Home},{id:'students',label:'Alunos',icon:Users},{id:'workouts',label:'Treinos',icon:CalendarDays},{id:'more',label:'Mais',icon:MoreHorizontal}] as const;
function useLocal<T,>(key:string, initial:T) {
  const [value,set] = useState<T>(() => {try {return JSON.parse(localStorage.getItem(key) || 'null') ?? initial;} catch {return initial;}});
  useEffect(() => {try {localStorage.setItem(key,JSON.stringify(value));} catch {/* The current session remains usable if browser storage is unavailable. */}}, [key,value]);
  return [value,set] as const;
}
function Avatar({student,large=false}:{student:Student;large?:boolean}) {return <span className={`avatar tone-${student.name.length % 4} ${large ? 'large' : ''}`}>{initials(student.name)}</span>;}
function Row({icon, title, subtitle, trailing, onClick}:{icon?:ReactNode; title:string; subtitle?:string; trailing?:ReactNode; onClick:()=>void}) {
  return <button className="action-row" onClick={onClick}>{icon && <span className="row-icon">{icon}</span>}<span className="row-text"><strong>{title}</strong>{subtitle && <small>{subtitle}</small>}</span>{trailing}<ChevronRight className="chevron" size={19}/></button>;
}
function App() {
  const [people,setPeople] = useLocal<Student[]>('vc-students-v3',seed);
  const [schedule,setSchedule] = useLocal<Schedule>('vc-schedule-v3',initialSchedule);
  const [page,setPage] = useState<Page>('home'), [selected,setSelected] = useState('1'), [detail,setDetail] = useState<Detail>('');
  const [athleteChosen,setAthleteChosen] = useState(false), [week,setWeek] = useState(0), [query,setQuery] = useState('');
  const [showFilters,setShowFilters] = useState(false), [level,setLevel] = useState('Todos'), [status,setStatus] = useState('Todos');
  const [moreDetail,setMoreDetail] = useState(''), [showCpf,setShowCpf] = useState(false), [login,setLogin] = useState(false);
  const [sheet,setSheet] = useState<Sheet>(null), [editor,setEditor] = useState<{day:number;workout:Workout;existing:boolean}|null>(null);
  const [studentForm,setStudentForm] = useState<{student:Student;step:number}|null>(null), [toast,setToast] = useState('');
  const student = people.find(p => p.id === selected) || people[0];
  const active = people.filter(p => p.status === 'Ativo');
  const todayAthletes = active.filter(p => (schedule[scheduleKey(p.id,0,3)] || []).length > 0);
  const birthdayToday = people.filter(p => p.birth.slice(5) === '10-08');
  const birthdays = people.filter(p => p.birth.slice(5,7) === '10' && Number(p.birth.slice(8)) >= 8).sort((a,b) => a.birth.slice(8).localeCompare(b.birth.slice(8)));
  const dues = active.filter(p => p.due >= 8 && p.due <= 15).sort((a,b) => a.due - b.due);
  const races = Array.from(new Set(people.filter(p => p.race && p.raceDate >= '2026-10-08').map(p => `${p.race}|${p.raceDate}`))).map(key => {
    const [name,date] = key.split('|'); return {name,date,athletes:people.filter(p => p.race === name && p.raceDate === date)};
  }).sort((a,b) => a.date.localeCompare(b.date));
  const upcomingRace = races[0];
  const notify = (message:string) => setToast(message);
  useEffect(() => {window.scrollTo({top:0});}, [page,detail,moreDetail]);
  useEffect(() => {if (!toast) return; const id = window.setTimeout(() => setToast(''),3200); return () => clearTimeout(id);},[toast]);
  function navigate(next:Page) {setPage(next);setQuery('');setDetail('');setShowFilters(false);setLevel('Todos');setStatus('Todos');setMoreDetail('');if(next === 'workouts')setAthleteChosen(false);window.scrollTo({top:0});}
  function profile(id:string) {setSelected(id);setDetail('');setShowCpf(false);setPage('profile');window.scrollTo({top:0});}
  function workouts(id:string, targetWeek=0) {setSelected(id);setWeek(targetWeek);setAthleteChosen(true);setPage('workouts');setQuery('');window.scrollTo({top:0});}
  function openMore(value:string) {navigate('more');setMoreDetail(value);}
  function openEditor(day:number, source=templates[0], existing=false) {setSheet(null);setEditor({day,workout:existing ? {...source} : cloneWorkout(source),existing});}
  function saveWorkout(workout:Workout) {
    if(!editor) return;
    setSchedule(current => saveSession(current, {studentId:selected, week, day:editor.day}, workout, editor.existing));
    notify(editor.existing ? 'Treino atualizado.' : 'Treino salvo.');
    setEditor(null);
  }
  function duplicateWeek() {
    const result = duplicatePreviousWeek(schedule, selected, week);
    setSheet(null);
    if(!result.count) {notify('A semana anterior não tem treinos.'); return;}
    setSchedule(result.schedule);
    notify(`${result.count} treinos adicionados. Os existentes foram mantidos.`);
  }
  function nextWorkout(p:Student) {return Object.entries(schedule).flatMap(([key,items]) => {const [id,w,d]=key.split(':');const date=weekDate(Number(w),Number(d));return id===p.id && date>=today ? items.map(workout => ({workout,date,week:Number(w)})) : [];}).sort((a,b)=>a.date.getTime()-b.date.getTime())[0];}
  const next = nextWorkout(student);
  const filtered = people.filter(p => normalize(`${p.name} ${p.goal} ${p.race}`).includes(normalize(query)) && (level==='Todos'||p.level===level) && (status==='Todos'||p.status===status));
  const filterCount = Number(level!=='Todos') + Number(status!=='Todos');
  const back = (label:string, action:()=>void) => <button className="back-button" onClick={action}><ArrowLeft size={18}/>{label}</button>;
  const studentList = (choose=false, list=filtered) => <div className="student-list">{list.map(p => <button className="student-row" onClick={()=>choose?workouts(p.id):profile(p.id)} key={p.id}><Avatar student={p}/><span className="row-text"><strong>{p.name}</strong><small>{p.goal} · {p.level}</small></span>{!choose && <span className="student-meta">{p.status==='Pausado'?<span className="muted">Pausado</span>:<>Vence dia {p.due}</>}</span>}<ChevronRight size={19} className="chevron"/></button>)}{!list.length && <div className="empty"><p>Nenhum aluno encontrado.</p><span>Tente outro nome ou ajuste os filtros.</span></div>}</div>;
  const searchBox = (placeholder='Buscar aluno') => <label className="search-box"><Search size={20}/><input type="search" aria-label={placeholder} placeholder={placeholder} value={query} onChange={e=>setQuery(e.target.value)}/>{query && <button aria-label="Limpar busca" onClick={()=>setQuery('')}><X size={17}/></button>}</label>;
  const activeNav = page==='profile'?'students':page;
  return <>{login ? <div className="login"><div className="brand-symbol">VC↗</div><h1>Olá, Vanderlei.</h1><p>Sua assessoria, do seu jeito.</p><button className="primary" onClick={()=>{setLogin(false);navigate('home');}}>Entrar na demonstração <ArrowRight size={20}/></button><small>Login fictício · sem senha</small></div> : <div className="app">
    <aside className="sidebar"><a href="#" className="brand" onClick={e=>{e.preventDefault();navigate('home');}}><span className="brand-symbol">VC↗</span><span>VANDERLEI COSTA<small>TREINADOR</small></span></a><nav aria-label="Navegação principal">{nav.map(({id,label,icon:Icon})=><button key={id} aria-current={activeNav===id?'page':undefined} className={activeNav===id?'active':''} onClick={()=>navigate(id)}><Icon size={21}/>{label}</button>)}</nav><div className="sidebar-end"><span className="coach-avatar">VC</span><div><strong>Vanderlei Costa</strong><small>Treinador</small></div></div></aside>
    <div className="workspace"><header className="mobile-header"><span className="brand-symbol">VC↗</span><span>Vanderlei Costa <small>Treinador</small></span><span className="demo-label">DEMO</span></header><div className="desktop-header"><span>{nav.find(n=>n.id===activeNav)?.label}</span><span>Protótipo local · 08 out. 2026</span></div>
      <main className={page==='workouts'&&athleteChosen?'wide-content':page==='more'||(page==='profile'&&detail)?'narrow-content':''}>
        {page==='home' && <div className="home-page"><div className="greeting"><span className="eyebrow">QUINTA, 8 DE OUTUBRO</span><h1>Bom dia, Vanderlei<span className="accent">.</span></h1><button className="active-count" onClick={()=>{navigate('students');setStatus('Ativo');}}>{active.length} alunos ativos <ChevronRight size={16}/></button></div>
          <button className="primary home-primary" onClick={()=>navigate('workouts')}><CalendarDays size={21}/> Planejar treinos <ArrowRight size={21}/></button>
          <section className="home-section"><h2>Hoje</h2><div className="row-group"><Row icon={<CalendarDays size={21}/>} title={`${todayAthletes.length} atletas com treino`} subtitle="Quinta-feira, 8 de outubro" onClick={()=>openMore('today')}/>{birthdayToday.length>0 && <Row icon={<Cake size={21}/>} title={`${birthdayToday.length} ${birthdayToday.length===1?'aniversário':'aniversários'}`} subtitle={birthdayToday.map(p=>p.name.split(' ')[0]).join(', ')} onClick={()=>openMore('birthdays')}/>}</div></section>
          <section className="home-section"><h2>Próximos</h2><div className="row-group"><Row icon={<Wallet size={21}/>} title={`${dues.length} vencimentos nos próximos 7 dias`} subtitle="Confira os planos dos alunos" onClick={()=>openMore('dues')}/>{upcomingRace && <Row icon={<Flag size={21}/>} title={upcomingRace.name} subtitle={`${shortDate(new Date(upcomingRace.date+'T12:00:00'))} · ${upcomingRace.athletes.length} atletas`} onClick={()=>openMore('races')}/>}</div></section>
          <button className="find-student" onClick={()=>navigate('students')}><Search size={19}/> Encontrar um aluno <ChevronRight size={18}/></button>
        </div>}
        {page==='students' && <><div className="page-title"><div><h1>Alunos</h1><p>{people.length} pessoas na sua assessoria</p></div><button className="primary" onClick={()=>setStudentForm({student:emptyStudent(people.length),step:0})}><Plus size={19}/> Novo aluno</button></div><div className="search-line">{searchBox()}<button className={`filter-button ${filterCount?'has-filter':''}`} aria-label={filterCount ? `Filtros, ${filterCount} ativos` : 'Filtros'} aria-expanded={showFilters} onClick={()=>setShowFilters(!showFilters)}><SlidersHorizontal size={19}/><span>Filtros{filterCount?` (${filterCount})`:''}</span></button></div>{showFilters && <div className="filter-panel"><label>Nível<select value={level} onChange={e=>setLevel(e.target.value)}>{['Todos','Iniciante','Intermediário','Avançado'].map(v=><option key={v}>{v}</option>)}</select></label><label>Status<select value={status} onChange={e=>setStatus(e.target.value)}>{['Todos','Ativo','Pausado'].map(v=><option key={v}>{v}</option>)}</select></label>{filterCount>0 && <button className="text-button" onClick={()=>{setLevel('Todos');setStatus('Todos');}}>Limpar filtros</button>}</div>}{!showFilters&&filterCount>0&&<button className="filter-summary" onClick={()=>setShowFilters(true)}>{[level!=='Todos'?level:'',status!=='Todos'?status:''].filter(Boolean).join(' · ')}<SlidersHorizontal size={15}/></button>}{studentList()}</>}
        {page==='profile' && <>{back(detail?student.name:'Alunos',()=>detail?setDetail(''):navigate('students'))}{!detail ? <>
          <div className="profile-intro"><Avatar student={student} large/><div><h1>{student.name}</h1><p>{student.goal} · {student.level}{student.status==='Pausado'?' · Pausado':''}</p></div></div>
          <button className="primary profile-primary" onClick={()=>workouts(student.id)}>Prescrever treino <Plus size={20}/></button>
          <section className="profile-summary"><div className="summary-top"><h2>Próximo treino</h2><span>Pace atual <b>{student.pace}/km</b></span></div>{next?<button className="next-workout" onClick={()=>workouts(student.id,next.week)}><span className="row-text"><small>{dayNames[(next.date.getDay()+6)%7]} · {shortDate(next.date)}</small><strong>{next.workout.title}</strong><span>{summary(next.workout)}</span></span><ChevronRight size={20}/></button>:<p className="empty-inline">Nenhum treino planejado.</p>}
            {student.race ? <div className="profile-race"><Flag size={18}/><div><small>Próxima prova</small><strong>{student.race}</strong><span>{dateLabel(student.raceDate)} · {student.raceDistance}</span></div></div> : <p className="empty-inline">Nenhuma prova cadastrada.</p>}
          </section>
          {student.medical && <div className="medical-note"><Heart size={18}/><div><strong>Atenção ao prescrever</strong><p>{student.medical}</p></div></div>}
          <section className="detail-links"><h2>Detalhes do aluno</h2><div className="row-group"><Row title="Dados cadastrais" onClick={()=>setDetail('data')}/><Row title="Avaliações" onClick={()=>setDetail('assessments')}/><Row title="Treinos" onClick={()=>workouts(student.id)}/><Row title="Plano" subtitle={`${student.plan} · ${money(student.value)}/mês`} onClick={()=>setDetail('plan')}/></div></section>
        </> : detail==='data' ? <><div className="page-title"><h1>Dados cadastrais</h1><button className="secondary" onClick={()=>setStudentForm({student:{...student},step:0})}>Editar</button></div>
          <section className="detail-section"><h2>Pessoal</h2><dl className="data-list">{[['Nome completo',student.name],['Nascimento',dateLabel(student.birth)],['Gênero',student.gender],['Camisa',student.shirt],['CPF',showCpf?student.cpf:'•••.•••.•••-••'],['Telefone',student.phone],['E-mail',student.email],['Endereço',`${student.street}, ${student.number}`],['Bairro',student.neighborhood],['Cidade / UF',`${student.city} / ${student.state}`],['Matrícula',student.enrollment]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value || 'Não informado'}{label==='CPF'&&<button className="text-button" onClick={()=>setShowCpf(!showCpf)}>{showCpf?'Ocultar':'Exibir exemplo'}</button>}</dd></div>)}</dl></section>
          <section className="detail-section"><h2>Corrida</h2><dl className="data-list">{[['Nível',student.level],['Objetivo',student.goal],['Pace atual',student.pace+'/km'],['Frequência',`${student.frequency} dias por semana`],['Tempo de corrida',student.experience],['Disponibilidade',student.availability],['Próxima prova',student.race||'Não informada'],['Data da prova',dateLabel(student.raceDate)],['Distância da prova',student.raceDistance||'Não informada']].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl></section><div className="medical-note"><Heart size={18}/><div><strong>Restrições médicas</strong><p>{student.medical||'Nenhuma informada.'}</p></div></div><section className="detail-section"><h2>Observações</h2><p>{student.notes||'Nenhuma observação cadastrada.'}</p></section>
        </> : detail==='assessments' ? <><div className="page-title"><div><h1>Avaliações</h1><p>Histórico de {student.name.split(' ')[0]}</p></div></div><p className="subtle-note">Exemplos ilustrativos, sem fórmulas. Exemplos de 1600 m, 2400 m e outro teste. Cooper também pode ser usado, conforme a avaliação do treinador.</p><div className="assessment-list">{assessments.map((a,i)=><details key={a.date} open={i===0}><summary><span><small>{dateLabel(a.date)}</small><strong>{a.type}</strong></span><span className="assessment-value">{a.vo2}<small>VO₂ máx</small></span><ChevronRight size={18}/></summary><dl><div><dt>Distância</dt><dd>{a.distance}</dd></div><div><dt>Tempo</dt><dd>{a.time}</dd></div><div><dt>FC máxima</dt><dd>{a.hr} bpm</dd></div></dl></details>)}</div></> : <><div className="page-title"><h1>Plano</h1></div><section className="plan-summary"><span className="eyebrow">PLANO ATUAL</span><h2>{student.plan}</h2><p className="price">{money(student.value)}<span>/ mês</span></p><div className="plan-line"><span>Vencimento</span><b>Dia {student.due}</b></div><div className="plan-line"><span>Status do aluno</span><b className={student.status==='Ativo'?'accent':''}>{student.status}</b></div><button className="secondary" onClick={()=>setStudentForm({student:{...student},step:2})}>Editar plano</button></section><p className="subtle-note">Registro do plano. Nenhuma cobrança é gerada.</p></> }</>}
        {page==='workouts' && (!athleteChosen ? <><div className="page-title"><div><h1>Treinos</h1><p>Para quem vamos planejar?</p></div></div>{searchBox('Buscar aluno para treinar')}{studentList(true)}</> : <>
          {back('Escolher outro aluno',()=>{setAthleteChosen(false);setQuery('');})}<div className="workouts-heading"><div><h1>{student.name}</h1><p>{student.goal} · {student.level}</p></div><button className="text-button" onClick={()=>profile(student.id)}>Ver perfil <ChevronRight size={17}/></button></div>
          <div className="week-toolbar"><div className="week-navigation"><button className="icon-button" aria-label="Semana anterior" onClick={()=>setWeek(week-1)}><ChevronLeft size={22}/></button><div><span>SEMANA</span><strong>{shortDate(weekDate(week,0))} — {shortDate(weekDate(week,6))}<small>{weekDate(week,0).getFullYear()===weekDate(week,6).getFullYear()?weekDate(week,0).getFullYear():`${weekDate(week,0).getFullYear()} / ${weekDate(week,6).getFullYear()}`}</small></strong></div><button className="icon-button" aria-label="Próxima semana" onClick={()=>setWeek(week+1)}><ChevronRight size={22}/></button></div><button className="icon-button week-options" aria-label="Opções da semana" onClick={()=>setSheet({type:'week'})}><MoreHorizontal size={22}/></button></div>{week!==0 && <button className="text-button current-week" onClick={()=>setWeek(0)}>Voltar para esta semana</button>}
          <div className="week-grid">{days.map(day=>{const items=schedule[scheduleKey(selected,week,day)]||[];return <section className="training-day" key={day}><div className="day-label"><h2>{dayNames[day]} <span>{weekDate(week,day).getDate()}</span></h2>{week===0&&day===3&&<span className="today-label">Hoje</span>}</div>{items.length ? items.map(w=><article className="workout-card" key={w.id}><div className="workout-card-title"><span className="workout-type">{w.type}</span><button className="icon-button" aria-label={`Opções de ${w.title}`} onClick={()=>setSheet({type:'workout',day,workout:w})}><MoreHorizontal size={21}/></button></div><h3>{w.title}</h3><p className="workout-summary">{summary(w)}</p><button className="edit-workout" onClick={()=>openEditor(day,w,true)}>Editar treino <ChevronRight size={17}/></button></article>) : <p className="no-workout">Nenhum treino por aqui.</p>}<button className="add-workout" onClick={()=>setSheet({type:'add',day})}><Plus size={19}/> Adicionar treino</button></section>;})}</div>
        </>)}
        {page==='more' && <>{moreDetail && back('Mais',()=>setMoreDetail(''))}<div className="page-title"><div><h1>{({dues:'Vencimentos',birthdays:'Aniversariantes',races:'Próximas provas',today:'Treinos de hoje'} as Record<string,string>)[moreDetail] || 'Mais'}</h1><p>{moreDetail==='dues'?'Próximos 7 dias · 8 a 15 de outubro':moreDetail==='birthdays'?'Próximos aniversários em outubro':moreDetail==='today'?'Quinta-feira, 8 de outubro':moreDetail==='races'?'Os próximos objetivos do seu time':'Quando você precisar.'}</p></div></div>{!moreDetail ? <><div className="row-group"><Row icon={<Wallet size={21}/>} title="Vencimentos" subtitle="Plano e dia de vencimento" onClick={()=>setMoreDetail('dues')}/><Row icon={<Cake size={21}/>} title="Aniversariantes" subtitle="Quem faz aniversário em breve" onClick={()=>setMoreDetail('birthdays')}/><Row icon={<Flag size={21}/>} title="Próximas provas" onClick={()=>setMoreDetail('races')}/></div><div className="demo-info"><span className="demo-label">PROTÓTIPO LOCAL</span><p>Dados fictícios. Alterações salvas neste navegador.</p><button className="text-button" onClick={()=>setLogin(true)}><LogOut size={17}/> Sair da demonstração</button></div></> : moreDetail==='dues' ? <div className="row-group">{dues.map(p=><Row key={p.id} title={p.name} subtitle={`${p.plan} · ${money(p.value)}/mês`} icon={<span className="date-icon"><small>OUT</small>{p.due}</span>} onClick={()=>{profile(p.id);setDetail('plan');}}/>)}{!dues.length&&<p className="empty">Nenhum vencimento nos próximos 7 dias.</p>}</div> : moreDetail==='birthdays' ? <div className="row-group">{birthdays.map(p=><Row key={p.id} title={p.name} subtitle={`${2026-Number(p.birth.slice(0,4))} anos · ${p.birth.slice(8)==='08'?'Hoje':p.birth.slice(8)+' de outubro'}`} icon={<Avatar student={p}/>} onClick={()=>profile(p.id)}/>)}{!birthdays.length&&<p className="empty">Nenhum aniversário próximo neste mês.</p>}</div> : moreDetail==='today' ? studentList(true,todayAthletes) : <div className="race-list">{races.map(r=><details key={r.name+r.date}><summary><Flag size={21}/><span><strong>{r.name}</strong><small>{dateLabel(r.date)} · {r.athletes.length} atletas</small></span><ChevronRight size={18}/></summary>{studentList(false,r.athletes)}</details>)}{!races.length&&<p className="empty">Nenhuma prova cadastrada.</p>}</div>}</>}
      </main>
    </div>
    <nav className="bottom-nav" aria-label="Navegação no celular">{nav.map(({id,label,icon:Icon})=><button key={id} aria-current={activeNav===id?'page':undefined} className={activeNav===id?'active':''} onClick={()=>navigate(id)}><Icon size={22}/><span>{label}</span></button>)}</nav>
  </div>}
  {sheet && <Modal compact key={sheet.type} title={sheet.type==='templates'?'Usar modelo':sheet.type==='add'?'Adicionar treino':sheet.type==='week'?'Opções da semana':sheet.type==='delete'?'Excluir treino?':sheet.workout.title} subtitle={sheet.type==='add'||sheet.type==='templates'?`${dayNames[sheet.day]}, ${shortDate(weekDate(week,sheet.day))}`:undefined} onClose={()=>setSheet(null)}>
    {sheet.type==='add' ? <div className="row-group sheet-choices"><Row icon={<Plus size={22}/>} title="Criar treino" subtitle="Preencher uma nova sessão" onClick={()=>openEditor(sheet.day)}/><Row icon={<Layers size={22}/>} title="Usar modelo" subtitle="Começar com um treino pronto" onClick={()=>setSheet({type:'templates',day:sheet.day})}/></div>
      : sheet.type==='templates' ? <div className="row-group sheet-choices">{templates.map(w=><Row key={w.id} title={w.title} subtitle={summary(w)} onClick={()=>openEditor(sheet.day,w)}/>)}</div>
      : sheet.type==='week' ? <><div className="row-group sheet-choices"><Row icon={<Copy size={21}/>} title="Duplicar semana anterior" subtitle="Adicionar os treinos anteriores a esta semana" onClick={duplicateWeek}/></div><p className="subtle-note">Todos os treinos da semana anterior serão adicionados aos mesmos dias desta semana. Os treinos existentes serão mantidos: nada será substituído, e dias já preenchidos também receberão cópias.</p></>
      : sheet.type==='delete' ? <>
        <p className="delete-context">Excluir <strong>{sheet.workout.title}</strong> de <strong>{student.name}</strong>, {dayNames[sheet.day].toLowerCase()}, {shortDate(weekDate(week,sheet.day))}?</p>
        <p className="subtle-note">Somente esta sessão será removida. Os outros treinos e o modelo original serão mantidos. Esta ação não pode ser desfeita.</p>
        <div className="sheet-actions"><button className="secondary" onClick={()=>setSheet({type:'workout',day:sheet.day,workout:sheet.workout})}>Cancelar</button><button className="danger-button" onClick={()=>{setSchedule(current=>deleteSession(current,{studentId:selected,week,day:sheet.day},sheet.workout.id));setSheet(null);notify('Treino excluído.');}}>Excluir treino</button></div>
      </> : <WorkoutActions workout={sheet.workout} onEdit={()=>openEditor(sheet.day,sheet.workout,true)} onDuplicate={()=>{setSchedule(current=>duplicateSession(current,{studentId:selected,week,day:sheet.day},sheet.workout));setSheet(null);notify('Treino duplicado no mesmo dia.');}} onDelete={()=>setSheet({type:'delete',day:sheet.day,workout:sheet.workout})}/>}

  </Modal>}
  {editor && <WorkoutEditor initial={editor.workout} editing={editor.existing} subtitle={`${student.name} · ${dayNames[editor.day]}, ${shortDate(weekDate(week,editor.day))}`} onClose={()=>setEditor(null)} onSave={saveWorkout}/>}
  {studentForm && <StudentForm initial={studentForm.student} editing={people.some(p=>p.id===studentForm.student.id)} initialStep={studentForm.step} onClose={()=>setStudentForm(null)} onSave={p=>{setPeople(people.some(s=>s.id===p.id)?people.map(s=>s.id===p.id?p:s):[...people,p]);setStudentForm(null);notify(people.some(s=>s.id===p.id)?'Cadastro atualizado.':'Aluno cadastrado.');}}/>}
  {toast && <div className="toast" role="status"><Check size={19}/>{toast}</div>}
  </>;
}
createRoot(document.getElementById('root')!).render(<App/>);
